### ISSUE TITLE
Lib can't be imported in Angular 13

### ISSUE THREAD

**Issue by delvinwidjaja** [spacycoder/ngx-vibration#35]
Hi, I'm trying to use this library for an Angular 13 App but it seems the module can't be imported in my AppModule.
![Screenshot 2022-09-09 at 11 45 39](https://user-images.githubusercontent.com/44110031/189322156-f196c547-c8c0-45be-b113-10677215fba1.png)

I opened the lib in node_modules and everything seems fine (except "experimentalDecorators", but it shouldn't be a problem i guess)

Could you please provide me some information how to fix this?

**Comment by delvinwidjaja** [comment]
Note: I forked the code and it has the same error message

**Comment by jornetsimon** [comment]
Just updated to Angular 17, with compatibility from Angular 13 onward. Can you please check again?
